---
driver_plugin: vagrant
platforms:
- name: debian-7
  driver_config:
    box: opscode-debian-7
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_debian-7.0.0_provisionerless.box
    require_chef_omnibus: 11.4.4

- name: debian-6
  driver_config:
    box: opscode-debian-6
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_debian-6.0.7_chef-11.2.0.box
    require_chef_omnibus: 11.4.4

- name: ubuntu-12.10
  driver_config:
    box: canonical-ubuntu-12.10
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.10_provisionerless.box
    require_chef_omnibus: 11.4.4

- name: ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: 11.4.4

- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
    require_chef_omnibus: 11.4.4

suites:
- name: default
  run_list:
  - recipe[push-jobs]
  attributes:
    push_jobs:
      package_url: "https://pushy-release.s3.amazonaws.com/1.0.0beta/opscode-push-jobs-client_0.0.1%2B20130307153525.git.98.c04f587-1.ubuntu.10.04_amd64.deb"
      whitelist: {chef-client: "chef-client"}
